name             'gilmour_health'
maintainer       'Piyush Verma'
maintainer_email 'piyush@piyushverma.net'
license          'All rights reserved'
description      'Installs/Configures gilmour_health'
long_description 'Installs/Configures gilmour_health'
version          '0.1.9'
depends          'ssh'
